### ISSUE TITLE
WHen save and SBML file, if user adds file extension .xml it is saved as model.xml.xml

### ISSUE THREAD

**Issue by bartjuw** [sys-bio/makesbml#3]
Need to check if user adds extension .xml to SBML file name to the model they are saving. If .xml is added by user than do not add .xml by default.

**Comment by bartjuw** [comment]
Fixed, added code check: if user's filename includes .xml or .txt then do not append .xml or .txt for sbml or antimony files.

**Comment by luciansmith** [comment]
I've also seen '.sbml' for SBML files.
